name: CI

on:
    pull_request:
        branches:
            - master

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - uses: actions/setup-node@v7
              with:
                  node-version: '24'
            - run: npm ci
            - name: Prettier check
              run: npm run format:check
            - name: Lint the code
              run: npm run lint
            - name: Build
              run: npm run build
            - name: Test
              run: npm test
